version: '1.0'
name: daily_build
displayName: daily_build
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-c55b27b6
    displayName: BuildProjet
    strategy: naturally
    trigger: auto
    executor:
      - qsaker
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: Build
        gccVersion: '10.3'
        commands:
          - apt-get update --fix-missing -y
          - apt-get install libgl1-mesa-dev -y
          - apt-get install qtbase5-dev -y
          - qmake -v
          - apt-get install libqt5charts5* -y
          - apt-get install libqt5serialbus5* -y
          - apt-get install libqt5websockets5* -y
          - apt-get install libqt5serialport5* -y
          - mkdir buildqt5
          - cd buildqt5
          - ls /usr/lib/x86_64-linux-gnu/cmake/
          - strip --remove-section=.note.ABI-tag /usr/lib64/libQt5Core.so.5
          - cmake --version
          - cmake -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5 -DCMAKE_BUILD_TYPE=Release ../ && make
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
