version: '1.0'
name: daily_build
displayName: daily_build
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-c55b27b6
    displayName: BuildProjet
    strategy: naturally
    trigger: auto
    executor:
      - qsaker
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: Build
        gccVersion: '9.4'
        commands:
          - '# 新建build目录，切换到build目录'
          - apt-get update --fix-missing -y
          - apt-get install libgl1-mesa-dev -y
          - apt-get install qt5-default -y
          - apt-get install libqt5websockets5 libqt5websockets5-dev -y
          - apt-get install libqt5serialport5 libqt5serialport5-dev -y
          - apt-get install libqt5charts5 libqt5charts5-dev -y
          - '# apt-get install qttools5-dev* -y'
          - '# apt-get install qttools5-private-dev -y'
          - 'mkdir build && cd build '
          - '# 生成Unix平台的makefiles文件并执行构建'
          - cmake -DQT_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5 -DQt5_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5 -G 'Unix Makefiles' ../ && make -j2
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
