version: '1.0'
name: daily_build
displayName: daily_build
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-c55b27b6
    displayName: BuildProjet
    strategy: naturally
    trigger: auto
    executor:
      - qsaker
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: Build
        gccVersion: '10.3'
        commands:
          - apt-get update --fix-missing -y
          - apt-get install libgl1-mesa-dev -y
          - apt-get install qtbase5-* -y
          - qmake -v
          - 'pip3 install aqtinstall   '
          - aqt install-qt linux desktop 6.5.3 gcc_64 -m qtcharts qtserialbus qtserialport
          - ''
          - cmake -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5 -DCMAKE_BUILD_TYPE:STRING=Release -G "CodeBlocks - Unix Makefiles" ../ -G "Unix Makefiles"
          - cmake --build . --target xTools
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
