version: '1.0'
name: pipeline-20211228
displayName: pipeline-20211228
triggers:
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-81c60419
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: gitee-go
        script: |-
          cd ~/gitee_go/deploy
          tar -zxvf output.tar.gz
          ls
          echo 'Hello Gitee!'
permissions:
  - role: admin
    members: []
