name: build-ubuntu
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'

jobs:
  build-test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v1
      - name: Install Tools for Qt5
        run: |
          sudo apt-get update --fix-missing -y
          sudo apt-get install libgl1-mesa-dev -y
          sudo apt-get install qtbase5-dev -y
          qmake -v
          sudo apt-get install libqt5charts5 libqt5charts5-dev -y
          sudo apt-get install libqt5serialbus5 libqt5serialbus5-dev -y
          sudo apt-get install libqt5serialport5 libqt5serialport5-dev -y
          sudo apt-get install libqt5websockets5 libqt5websockets5-dev -y
      - name: Build with Qt5
        run: |
          mkdir build && cd build
          cmake --version
          cmake -DQT_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5 -DQt5_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5 -DCMAKE_BUILD_TYPE="Release" ../ && make -j2

