name: build-ios
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
        version: [5.15.2, 6.5.3]
        arch: [ios]
        include:
          - version: 5.15.2
            cmake-prefix-path: 'lib/cmake/Qt5'
            modules: 'qtcharts'
          - version: 6.5.3
            cmake-prefix-path: 'lib/cmake/Qt6'
            moudles: 'qtcharts qtserialbus qtserialport qtwebsockets'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install qt for desktop
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          dir: ${{ github.workspace }}
          version: ${{ matrix.version }}
          modules: ${{ matrix['moudles']}}
      - name: install qt for ios
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ matrix.version }}
          target: 'ios'
          arch: ${{ matrix.arch }}
          dir: ${{ github.workspace }}
          host: 'mac'
          modules: ${{ matrix['moudles']}}
      - name: build for macos
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}/${{ matrix.cmake-prefix-path }}' -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../
          make
