name: build-daily
on: push
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  new-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Delete old release
      uses: liudonghua123/delete-release-action@v1
      with:
        release_name: 'continuous'
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: 'continuous'
        allowUpdates: true
  build-for-windows:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: ${{ github.workspace }}
        modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
    - name: Build for Windows
      shell: cmd
      run: |
        mkdir build
        cd build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/6.5.3/win64_msvc2019_64/lib/cmake/Qt6' -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ../
        nmake
    - name: Upload Release Asset for Windnows
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: 'continuous'
        path: 'build/sak/qtswissarmyknife-windows-amd64.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}