name: build-daily
on: push

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: continuous