name: build-daily
on: push
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-delete:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { owner, repo } = context.repo
          const { data: { id } } = await github.repos.getLatestRelease({ owner, repo })
          await github.repos.deleteRelease({ owner, repo, release_id: id })
  release-new:
    runs-on: ubuntu-latest
    needs: release-delete
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: 'continuous'
        allowUpdates: true
  release-for-windows:
    runs-on: windows-2019
    needs: release-new
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: ${{ github.workspace }}
        modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
    - name: Build for Windows
      shell: cmd
      run: |
        mkdir build
        cd build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/6.5.3/win64_msvc2019_64/lib/cmake/Qt6' -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ../
        cmake build . --target QtSwissArmyKnife
        dir
    - name: Upload Release Asset for Windnows
      uses: Shopify/upload-to-release@v1.0.1
      with:
        name: 'continuous'
        path: 'build/sak/qtswissarmyknife-windows-amd64.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}