name: build-daily
on: push

jobs:
  new-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Delete Release
      uses: liudonghua123/delete-release-action@v1
      with:
        release_name: 'continuous'
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: continuous
 