name: build-ubuntu
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'

jobs:
  build-test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        qt: [5, 6]
        exclude:
          - os: ubuntu-20.04
            qt: 6
    steps:
      - uses: actions/checkout@v1
      - name: Call buildwithqt5.sh
        run: |
          sudo chmod +x buildwithqt${{ matrix.qt }}.sh
          sudo ./buildwithqt${{ matrix.qt }}.sh

