name: build-daily
on: push

jobs:
  new-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Delete Release
      uses: actions/github-script@v5
      with:
        script: |
          const { owner, repo } = context.repo
          const releases = await github.repos.listReleases({ owner, repo })
          const release = releases.data.find(release => release.tag_name === 'continuous')
          if (release) {
            await github.repos.deleteRelease({ owner, repo, release_id: release.id })
          }
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: continuous
 