name: build-ios
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'

jobs:
  build:
    name: Build
    runs-on: macos-10.15
    strategy:
      matrix:
        qt_ver: [5.12.10, 5.15.2]
        qt_target: [ios]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2017_64'
          dir: '${{ github.workspace }}/example/'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
          cached: 'false'
          setup-python: 'true'
          tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
          set-env: 'false'
          tools-only: 'false'
          aqtversion: '==0.10.1'
          py7zrversion: '==0.11.1'
          extra: '--external 7z'
      - name: build ios
        run: |
          qmake -r -spec macx-ios-clang CONFIG+=release CONFIG+=iphoneos
          make
