name: build-android
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu22.04
    strategy:
      matrix:
        arch: [android_armv7, android_arm64_v8a, android_x86, android_x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          target: 'android'
          host: 'linux'
          modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
          arch: ${{ matrix.arch }}
      - name: Build for Android(${{ matrix.arch }})
        run: |
          mkdir build
          cd build
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}/lib/cmake/Qt6' -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ../
          make

