name: build-android
on: push
#  schedule:
#    - cron: '0 0 * * *'
env:
  JAVA_HOME: $JAVA_HOME_11_X64
  CMAKE_MAKE_PROGRAM: ${{ github.workspace }}/resources/tools/ninja.exe
  ANDROID_NDK_ROOT: $ANDROID_NDK_ROOT
  ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT

jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      matrix:
        target: [android]
        arch: [android_armv7]
        version: [6.5.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.version }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          dir: ${{ github.workspace }}
          modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
      - name: Build for Android
        shell: cmd
        run: |
          ${{ github.workspace }}\Qt\${{matrix.version}}\${{matrix.arch}}\bin\qt-cmake.bat ^
          -G Ninja ^
          -S . ^
          -B "build\armeabi_v7a" ^
          -DCMAKE_BUILD_TYPE:STRING=Release ^
          -DCMAKE_MAKE_PROGRAM:FILEPATH="${{env.CMAKE_MAKE_PROGRAM}}" ^
          -DCMAKE_CXX_COMPILER:FILEPATH="${{env.ANDROID_NDK_ROOT}}/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe" ^
          -DANDROID_SDK_ROOT:PATH="${{env.ANDROID_SDK_ROOT}}" ^
          -DANDROID_NDK_ROOT="${{env.ANDROID_NDK_ROOT}}"