name: build-windows
# on:
#   schedule:
#     - cron: '0 0 * * *'
on:
 push:
   branches:
     - master
jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      matrix:
        target: [desktop]
        arch: [win64_msvc2022_64]
        version: [6.8.*]
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.version }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          dir: ${{ github.workspace }}
          modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
      - name: build-msvc
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}' -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ../
          nmake
