name: build-android
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        #arch: [android_armv7, android_arm64_v8a, android_x86, android_x86_64]
        arch: [android_armv7]
        version: [6.5.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          host: 'linux'
          target: 'android'
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
          dir: ${{ github.workspace }}
      - name: Build for Android
        env: 
          JAVA_HOME: $JAVA_HOME_11_X64
        run: |
          aqt install-qt linux desktop ${{ matrix.version }} gcc_64
          mkdir build
          cd build
          cmake -DQT_DIR='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}/lib/cmake/Qt6' -DQt6_DIR='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}/lib/cmake/Qt6' -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../
          make

