name: build-ios
on: push
#  schedule:
#    - cron: '0 0 * * *'
env:
  QT_VERSION: 6.5.3
  QT_MODULES: 'qtcharts qtserialbus qtserialport qtwebsockets'
jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install qt for desktop
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          dir: ${{ github.workspace }}
          version:  ${{ env.QT_MODULES }}
          modules: ${{ env.QT_MODULES }}
      - name: install qt for ios
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          host: 'mac'
          target: 'ios'
          arch: 'ios'
          dir: ${{ github.workspace }}
          version:  ${{ env.QT_MODULES }}
          modules: ${{ env.QT_MODULES }}
      - name: build for macos
        run: |
          ${{ github.workspace }}\Qt\${{env.QT_VERSION}}\ios\bin\qt-cmake -G "MinGW Makefiles" -S . -B "build/ios" -DCMAKE_BUILD_TYPE=Release
          cmake --build "build/ios" --config Release
          tree build/ios
