name: update-continuous-tag

on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update continuous tag
        env:
          GH_TOKEN: ${{ secrets.SAK_ACTIONS_SECRETS }}
        run: |
          git config --global user.email "qsaker@foxmail.com"
          git config --global user.name "Qsaker"
          git tag -fa continuous -m "chore: update to latest commit"
          git push origin :refs/tags/continuous
          git commit --allow-empty -m "Trigger GitHub Actions"
          git push origin continuous